esphome:
  name: <your data>
  
  libraries:
    - "https://github.com/Bunicutz/ESP32_Midea_RS485.git"

esp32:
  board: <your data>
  framework:
    type: arduino

# Enable logging
logger:

ota:
  - platform: esphome
    password: "xxxxxx"

api:

wifi:
  networks:
  - ssid: <your data>
  - password: <your data>

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "<your data>"
    password: "<your data>"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: <your data>
   # Set this to the IP address of the router. Often ends with .1
    gateway: <your data>
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: <your data>

captive_portal:

mqtt:
  broker: <your data>
  port: <your data>
  username: <your data>
  password: <your data>
  keepalive: 1min
  discovery: true
  discovery_retain: true

external_components:
  - source: 
      type: local
      path: external_components

Bunicutz_AC:
  id: "WholeHouse_AC"
  Unknown1:
    name: "AC Unknown1"
  Capabilities:
    name: "AC Capabilities"
  ACT1Temp:
    name: "AC In Air Temp"
  ACT2ATemp:
    name: "AC Coil A Temp"
  ACT2BTemp:
    name: "AC Coil B Temp"
  ACT3Temp:
    name: "AC Outdoor Temp"
  Current:
    name: "AC Current"
  Unknown2:
    name: "AC Unknown2"
  Unknown3:
    name: "AC Unknown3"
  OperatingFlags:
    name: "AC Operating Flags"
  ErrorFlags:
    name: "AC Error Flags"
  ProtectFlags:
    name: "AC Protect Flags"
  CCMComErrorFlags:
    name: "AC CCM Com Error Flags"
  Unknown4:
    name: "AC Unknown4"
  Unknown5:
    name: "AC Unknown5"
  ACNotResponding:
    name: "AC Com State"

switch:
  - platform: Bunicutz_AC
    aux_heat:
      name: "Auxiliary Heat"
    echo_sleep:
      name: "Echo/Sleep"
    swing:
      name: "Swing"
    vent:
      name: "Vent"
    lock:
      name: "Lock"

select:
  - platform: Bunicutz_AC
    SetMode:
      name: "AC Mode"
    SetFanMode:
      name: "AC Fan Mode"

number:
  - platform: Bunicutz_AC
    SetTemp:
      name: "AC Set Temp"