#........................................................

  includes: 
    - bunicutz_AC.h
  
  libraries:
    - "https://github.com/Bunicutz/ESP32_Midea_RS485.git"

#..............................................

sensor:
- platform: custom
  id: my_AC
  lambda: |-
    auto my_ACSensors = new BunicutzACSensor(id(my_ac_mode),id(my_ac_fan_mode),id(ac_set_temp),id(ac_aux_heat),id(ac_echo_sleep),id(ac_vent),id(ac_swing),id(ac_lock));
    App.register_component(my_ACSensors);
    return {my_ACSensors->ACT1Temp,
            my_ACSensors->ACT2ATemp,
            my_ACSensors->ACT2BTemp,
            my_ACSensors->ACT3Temp,
            my_ACSensors->ACNotResponding
    };
  sensors:
  - name: "AC In Air Temp"    
    unit_of_measurement: "°C"
    accuracy_decimals: 0

  - name: "AC Coil A Temp"    
    unit_of_measurement: "°C"
    accuracy_decimals: 0

  - name: "AC Coil B Temp"    
    unit_of_measurement: "°C"
    accuracy_decimals: 0

  - name: "AC Outdoor Temp"    
    unit_of_measurement: "°C"
    accuracy_decimals: 0

  - name: "AC Com State"    
    unit_of_measurement: "bool"
    accuracy_decimals: 0

select:
  - platform: template
    name: "AC Mode"
    optimistic: true
    id: my_ac_mode
    options:
      - "Off"
      - "Auto"
      - "Cool"
      - "Dry"
      - "Heat"
      - "Fan"
      - "Unknown"

  - platform: template
    name: "AC Fan Mode"
    optimistic: true
    id: my_ac_fan_mode
    options:
      - "Auto"
      - "High"
      - "Medium"
      - "Low"
      - "Unknown"

number:
  - platform: template
    name: "AC Set Temp"
    id: ac_set_temp
    optimistic: true
    min_value: 18
    max_value: 32
    step: 1

switch:
  - platform: template
    name: "Auxiliary Heat"
    id: ac_aux_heat
    optimistic: true

  - platform: template
    name: "Echo/Sleep"
    id: ac_echo_sleep
    optimistic: true

  - platform: template
    name: "Swing"
    id: ac_swing
    optimistic: true

  - platform: template
    name: "Vent"
    id: ac_vent
    optimistic: true

  - platform: template
    name: "Lock"
    id: ac_lock
    optimistic: true
